swagger:  "2.0" 
info:
  description:  Trade
  version:  0.0.0 
  title:  Trade API
  contact:
    email:  pavel.ramasheuski@gmail.com
host:  localhost:3000
tags:
- name:  authentication 
  description:  Need to add more statuses
schemes:
-  http 
basePath:  /api 
paths:
  /account/signUp:
    post:
      summary: (user)
      tags:
      -  authentication 
      description:  Allow to signUP in app
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            username:
              type:  string 
            email:
              type:  string 
            password:
              type:  string 
      responses:
        200:
          description:  Successful login 
          schema: 
            $ref:  "#/definitions/Token" 
        500:
          description:  Unhandled server error 
  /account/login:
    post:
      summary: (user)
      tags:
      -  authentication 
      description:  Allow to login in app, return user info and set cookie 
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            username:
              type:  string 
            password:
              type:  string 
      responses:
        200:
          description:  Successful login 
          schema: 
            $ref:  "#/definitions/Token" 
        500:
          description:  Unhandled server error 

  /user:
    get:
      summary: (user)
      tags:
        -  user 
      description:  Return current user info
      responses:
        200:
          description:  Successfull operation 
          schema: 
            $ref:  "#/definitions/UserInfo" 
        500:
          description:  Unhandled server error 

  /user/ads:
    get:
      summary: (user)
      tags:
        -  user 
      description:  Return current user ads
      responses:
        200:
          description:  Successfull operation 
          schema: 
            type: array
            items:
              $ref:  "#/definitions/Ads" 
        500:
          description:  Unhandled server error 

  /user/changePassword:
    post:
      summary: (user)
      tags:
        -  user 
      description:  Return user info
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            oldPassword:
              type:  string 
            newPassword:
              type:  string
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error
  /user/balanceUp:
    post:
      summary: (user)
      tags:
        -  user 
      description:  Allows to up user balance
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            balanceChange:
              type:  number 
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error  

  /user/{username}:
    get:
      summary: (user)
      tags:
        -  user 
      description:  Return user with "username" info
      responses:
        200:
          description:  Successfull operation 
          schema: 
            $ref:  "#/definitions/UserInfo" 
        500:
          description:  Unhandled server error 

  /user/{username}/ads:
    get:
      summary: (user)
      tags:
        -  user 
      description: Return user with "username" ads
      responses:
        200:
          description:  Successfull operation 
          schema: 
            type: array
            items:
              $ref:  "#/definitions/Ads" 
        500:
          description:  Unhandled server error 

  /ad:
    get:
      summary: (user)
      tags:
        -  ad
      description:  Return array of all ads
      responses:
        200:
          description:  Successfull operation 
          schema: 
            type: array
            items:
              $ref:  "#/definitions/Ads" 

        500:
          description:  Unhandled server error         
  /ad/create:
    post:
      summary: (user)
      tags:
        -  ad
      description:  Allows for user to create ad
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            description:
              type:  string 
            price:
              type:  number
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error  

  /ad/{adID}:
    get:
      summary: (user)
      tags:
        -  ad
      description:  Return ad with adID
      responses:
        200:
          description:  Successfull operation 
          schema: 
              $ref:  "#/definitions/Ads" 
        500:
          description:  Unhandled server error  
           
  /ad/{adID}/buy:
    post:
      summary: (user)
      tags:
        -  ad
      description:  Allows for user to buy ad with adID, update balance of customer and ad creator
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            _id:
              type:  string 
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error  


definitions:
  Token: 
    type: object
    properties: 
      token: 
        type: string
  UserInfo:
    type: object
    properties: 
      username: 
        type: string
      email: 
        type: string
      balance: 
        type: string
  Ads:
    type: object
    properties: 
      creator: 
        type: string
      customer: 
        type: string
      description: 
        type: string
      timeOfCreation:
        type: string
      isOpened:
        type: boolean
      price:
        type: number

