swagger:  "2.0" 
info:
  description:  Trade
  version:  0.0.0 
  title:  Trade API
  contact:
    email:  pavel.ramasheuski@gmail.com
host:  localhost:3000
tags:
- name:  authentication 
  description:  Need to add more statuses
schemes:
-  http 
basePath:  /api 
paths:
  /account/signUp:
    post:
      summary: (user)
      tags:
      -  authentication 
      description:  Allow to signUP in app
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            username:
              type:  string 
            email:
              type:  string 
            password:
              type:  string 
      responses:
        200:
          description:  Successful login 
          schema: 
            $ref:  "#/definitions/Token" 
        500:
          description:  Unhandled server error 
  /account/login:
    post:
      summary: (user)
      tags:
      -  authentication 
      description:  Allow to login in app, return user info and set cookie 
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            username:
              type:  string 
            password:
              type:  string 
      responses:
        200:
          description:  Successful login 
          schema: 
            $ref:  "#/definitions/Token" 
        500:
          description:  Unhandled server error 

  /user:
    get:
      summary: (user)
      tags:
        -  user 
      description:  Return current user info
      responses:
        200:
          description:  Successfull operation 
          schema: 
            $ref:  "#/definitions/UserInfo" 
        500:
          description:  Unhandled server error 

  /user/ads:
    get:
      summary: (user)
      tags:
        -  user 
      description:  Return current user ads
      responses:
        200:
          description:  Successfull operation 
          schema: 
            type: array
            items:
              $ref:  "#/definitions/Ad" 
        500:
          description:  Unhandled server error 

  /user/changePassword:
    post:
      summary: (user)
      tags:
        -  user 
      description:  Return user info
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            oldPassword:
              type:  string 
            newPassword:
              type:  string
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error
  /user/balanceUp:
    post:
      summary: (user)
      tags:
        -  user 
      description:  Allows to up user balance
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            balanceChange:
              type:  number 
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error  

  /user/{username}:
    get:
      summary: (user)
      tags:
        -  user 
      description:  Return user with "username" info
      responses:
        200:
          description:  Successfull operation 
          schema: 
            $ref:  "#/definitions/UserInfo" 
        500:
          description:  Unhandled server error 

  /user/{username}/ads:
    get:
      summary: (user)
      tags:
        -  user 
      description: Return user with "username" ads
      responses:
        200:
          description:  Successfull operation 
          schema: 
            type: array
            items:
              $ref:  "#/definitions/Ad" 
        500:
          description:  Unhandled server error 
  /user/{username}/comments:
    get:
      summary: (user)
      tags:
        -  comments on user
      description:  Allows for user to get comments on user by his username
      responses:
        200:
          description:  Successfull operation 
          schema: 
            type: array
            items:
              $ref:  "#/definitions/Comment"
        500:
          description:  Unhandled server error  
    post:
      summary: (user)
      tags:
        - comments on user
      description:  Allows for user to left comment on user by username
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            message:
              type:  string 
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error 

  /ads:
    get:
      summary: (user)
      tags:
        -  ads
      description:  Return array of ads by page and amount of ads perPage
      parameters:
      - in:  query 
        name:  page    
        type:  number 
      - in:  query 
        name:  perPage    
        type:  number 
      responses:
        200:
          description:  Successfull operation 
          schema: 
            type: object
            properties: 
              ads:
                type: array
                items:
                  $ref:  "#/definitions/Ad" 
              pages: 
                type: number

        500:
          description:  Unhandled server error         
  /ads/create:
    post:
      summary: (user)
      tags:
        -  ads
      description:  Allows for user to create ad
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            description:
              type:  string 
            link:
              type:  string 
            price:
              type:  number
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error  

  /ads/{adID}:
    get:
      summary: (user)
      tags:
        -  ads
      description:  Return ad with adID
      responses:
        200:
          description:  Successfull operation 
          schema: 
              $ref:  "#/definitions/Ad" 
        500:
          description:  Unhandled server error  

  /ads/{adID}/buy:
    put:
      summary: (user)
      tags:
        -  ads
      description:  Allows for user to buy ad with adID, update balance of customer and ad creator
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error  

  /ads/{adID}/comments:
    get:
      summary: (user)
      tags:
        -  comments on ad
      description:  Allows for user to get comments on ad with adID
      responses:
        200:
          description:  Successfull operation 
          schema: 
            type: array
            items:
              $ref:  "#/definitions/Comment"
        500:
          description:  Unhandled server error  
    post:
      summary: (user)
      tags:
        -  comments on ad
      description:  Allows for user to left comment on ad with adID
      parameters:
      - in:  body 
        name:  body 
        required: true    
        schema:             
          type:  object 
          properties:
            message:
              type:  string 
      responses:
        200:
          description:  Successfull operation 
        500:
          description:  Unhandled server error 


definitions:
  Token: 
    type: object
    properties: 
      token: 
        type: string
  UserInfo:
    type: object
    properties: 
      username: 
        type: string
      email: 
        type: string
      balance: 
        type: string
  Ad:
    type: object
    properties: 
      creator: 
        type: string
      customer: 
        type: string
      description: 
        type: string
      timeOfCreation:
        type: string
      isOpened:
        type: boolean
      price:
        type: number
      amountOfSubscribers:
        type: number
      link: 
        type: string
        
  Comment:
    type: object
    properties: 
      username: 
        type: string
      date: 
        type: string
      message: 
        type: string


